version: "3.3"

volumes:
    mothership_registry_data:
        external: true
    mothership_registry_certs:
        external: true
    mothership_registry_config:
        external: true

networks:
    mothership:
        external: true

services:
    registry:
        image: registry:2
        networks:
            - mothership
        volumes:
            - mothership_registry_certs:/certs:ro
            - mothership_registry_config:/etc/docker/registry:ro
            - mothership_registry_data:/var/lib/registry
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.role == manager
