version: "3.3"

volumes:
    registry_data:
        external: true
    registry_config:
        external: true
    registry_auth_log:
        external: true
    registry_auth_config:
        external: true

networks:
    mothership:
        external: true

services:
    registry:
        image: registry:2
        networks:
            - mothership
        volumes:
            - /etc/mothership/certs:/certs:ro
            - registry_config:/etc/docker/registry:ro
            - registry_data:/var/lib/registry
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.role == manager

    registry_auth:
        image: cesanta/docker_auth:1.3
        networks:
            - mothership
        volumes:
            - /etc/mothership/certs:/certs:ro
            - registry_auth_config:/config:ro
            - registry_auth_log:/logs:rw
        command: /config/auth.ldap.yml
        # for debig: --v=2 --alsologtostderr /config/auth.ldap.yml
