version: "3.3"

volumes:
    registry_data:
        external: true

services:
    registry:
        image: registry:2
        volumes:
            - registry_data:/var/lib/registry
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.role == manager
