version: "3.3"

volumes:
    xwiki_data:
        external: true
    xwiki_mysql:
        external: true

networks:
    xwiki:
    mothership:
        external: true

services:
    mysql:
        image: newtoncodes/mysql:5.7
        networks:
            - xwiki
        volumes:
            - xwiki_mysql:/var/lib/mysql
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.role == manager

    xwiki:
        image: xwiki:9.11.1
        networks:
            - xwiki
            - mothership
        environment:
            - DB_DATABASE=xwiki
            - DB_USER=xwiki
            - DB_PASSWORD={{PASSWORD}}
            - DB_HOST=mysql
        volumes:
            - xwiki_data:/usr/local/xwiki
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.role == manager
