version: "3.3"

volumes:
    nextcloud_data:
        external: true
    nextcloud_mysql:
        external: true

networks:
    nextcloud:
    mothership:
        external: true

services:
    mysql:
        image: newtoncodes/mysql:5.7
        networks:
            - nextcloud
        volumes:
            - nextcloud_mysql:/var/lib/mysql
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.role == manager

    nextcloud:
        image: newtoncodes/nextcloud:16.0
        networks:
            - nextcloud
            - mothership
        volumes:
            - nextcloud_data:/var/www/html
        environment:
            - MYSQL_HOST=mysql
            - MYSQL_PASSWORD={{PASSWORD}}
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.role == manager
