version: "3.3"

volumes:
    mothership_nextcloud_data:
        external: true
    mothership_nextcloud_mysql:
        external: true

networks:
    mothership:
        external: true

services:
    nextcloud_mysql:
        image: newtoncodes/mysql:5.7
        networks:
            - mothership
        volumes:
            - mothership_nextcloud_mysql:/var/lib/mysql
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.role == manager

    nextcloud:
        image: nextcloud:12
        networks:
            - mothership
        volumes:
            - mothership_nextcloud_data:/var/www/html
        environment:
            - MYSQL_HOST=nextcloud_mysql
            - MYSQL_PASSWORD={{PASSWORD}}
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.role == manager
