version: "3.3"

volumes:
    bookstack_uploads:
        external: true
    bookstack_storage:
        external: true
    bookstack_mysql:
        external: true

networks:
    mothership:
        external: true

services:
    mysql:
        image: newtoncodes/mysql:5.7
        hostname:
            - bookstack_mysql
        networks:
            - mothership
        volumes:
            - bookstack_mysql:/var/lib/mysql
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.role == manager

    bookstack:
        image: newtoncodes/bookstack:0.19.0
        networks:
            - mothership
        environment:
            - DB_HOST=bookstack_mysql
            - DB_PASSWORD={{PASSWORD}}
        volumes:
            - bookstack_uploads:/var/www/bookstack/public/uploads
            - bookstack_storage:/var/www/bookstack/public/storage
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.role == manager
