version: "3.3"

volumes:
    bookstack_uploads:
        external: true
    bookstack_storage:
        external: true
    bookstack_mysql:
        external: true

networks:
    bookstack:
        external: true

services:
    db:
        image: newtoncodes/mysql:5.7
        networks:
            - bookstack
        volumes:
            - bookstack_mysql:/var/lib/mysql
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.role == manager

    bookstack:
        image: newtoncodes/bookstack:0.19.0
        networks:
            - bookstack
        environment:
            - DB_HOST=db
            - DB_PASSWORD=parola123
        volumes:
            - bookstack_uploads:/var/www/bookstack/public/uploads
            - bookstack_storage:/var/www/bookstack/public/storage
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.role == manager

    nginx:
        image: newtoncodes/nginx
        ports:
            - 443:443
            - 80:80
        networks:
            - bookstack
        volumes:
            - /etc/mothership/bookstack/vhost.conf:/etc/nginx/vhosts/default.conf

    snet:
        image: newtoncodes/snet:1.0.0
        networks:
            - bookstack
        environment:
            - PORTS=80:bookstack:80 443:bookstack:443
        volumes:
            - /etc/mothership/bookstack/vpn:/etc/snet
