version: "3.3"

volumes:
    nextcloud_data:
        external: true
    nextcloud_mysql:
        external: true

networks:
    nextcloud:
        external: true

services:
    db:
        image: newtoncodes/mysql:5.7
        networks:
            - nextcloud
        volumes:
            - nextcloud_mysql:/var/lib/mysql
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.role == manager

    nextcloud:
        image: nextcloud:12
        networks:
            - nextcloud
        volumes:
            - nextcloud_data:/var/www/html
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.role == manager
