version: "3.3"

volumes:
    nextcloud_data:
        external: true
    nextcloud_mysql:
        external: true

networks:
    nextcloud:
        external: true

services:
    db:
        image: newtoncodes/mysql:5.7
        networks:
            - nextcloud
        volumes:
            - nextcloud_mysql:/var/lib/mysql
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.role == manager

    nextcloud:
        image: nextcloud:12
        networks:
            - nextcloud
        volumes:
            - nextcloud_data:/var/www/html
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.role == manager

    nginx:
        image: newtoncodes/nginx
        ports:
            - 443:443
            - 80:80
        networks:
            - nextcloud
        volumes:
            - /etc/mothership/nextcloud/vhost.conf:/etc/nginx/vhosts/default.conf

    snet:
        image: newtoncodes/snet:1.0.0
        networks:
            - nginx
        environment:
            - PORTS=80:nginx:80 443:nginx:443
        volumes:
            - /etc/mothership/nextcloud/vpn:/etc/snet
