version: "3.3"

volumes:
    ldap_config:
        external: true
    ldap_data:
        external: true
    ldap_certs:
        external: true
    ldap_admin:
        external: true

networks:
    mothership:
        external: true

services:
    ldap:
        image: osixia/openldap:1.1.11
        networks:
            - mothership
        ports:
            - 389:389
            - 636:636
        environment:
            LDAP_LOG_LEVEL: "256"
            LDAP_ORGANISATION: "{{DOMAIN}}"
            LDAP_DOMAIN: "{{DOMAIN}}"
            LDAP_ADMIN_PASSWORD: "admin"
            LDAP_CONFIG_PASSWORD: "config"
            LDAP_READONLY_USER: "false"
            LDAP_RFC2307BIS_SCHEMA: "false"
            LDAP_BACKEND: "hdb"
            LDAP_TLS: "true"
            LDAP_TLS_CRT_FILENAME: "ldap.crt"
            LDAP_TLS_KEY_FILENAME: "ldap.key"
            LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
            LDAP_TLS_ENFORCE: "false"
            LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
            LDAP_TLS_PROTOCOL_MIN: "3.1"
            LDAP_TLS_VERIFY_CLIENT: "try"
            LDAP_REPLICATION: "false"
            #LDAP_REPLICATION_CONFIG_SYNCPROV: "binddn="cn=admin,cn=config" bindmethod=simple credentials=$LDAP_CONFIG_PASSWORD searchbase="cn=config" type=refreshAndPersist retry="60 +" timeout=1 starttls=critical"
            #LDAP_REPLICATION_DB_SYNCPROV: "binddn="cn=admin,$LDAP_BASE_DN" bindmethod=simple credentials=$LDAP_ADMIN_PASSWORD searchbase="$LDAP_BASE_DN" type=refreshAndPersist interval=00:00:00:10 retry="60 +" timeout=1 starttls=critical"
            #LDAP_REPLICATION_HOSTS: "#PYTHON2BASH:['ldap://ldap.example.org','ldap://ldap2.example.org']"
            KEEP_EXISTING_CONFIG: "false"
            LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
            LDAP_SSL_HELPER_PREFIX: "ldap"
        tty: true
        stdin_open: true
        volumes:
            - ldap_config:/etc/ldap/slapd.d
            - ldap_data:/var/lib/ldap
            - ldap_certs:/container/service/slapd/assets/certs

    ldapadmin:
        image: newtoncodes/ldap-account-manager:5.2
        networks:
            - mothership
        volumes:
            - ldap_admin:/var/lib/ldap-account-manager
        depends_on:
            - ldap
