version: "3.3"

volumes:
    mothership_iredmail_vmail:
        external: true
    mothership_iredmail_clamav:
        external: true
    mothership_iredmail_mysql:
        external: true

networks:
    mothership:
        external: true

services:
    iredmail:
        image: newtoncodes/iredmail:0.9.7
        ports:
            - 25:25
            - 587:587
            - 110:110
            - 143:143
            - 993:993
            - 995:995
        networks:
            - mothership
        volumes:
            - mothership_iredmail_vmail:/var/vmail
            - mothership_iredmail_clamav:/var/lib/clamav
            - mothership_iredmail_mysql:/var/lib/mysql
        environment:
            - SOGO_WORKERS=2
            - DOMAIN={{DOMAIN}}
            - HOSTNAME={{HOSTNAME}}
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.role == manager
            resources:
                limits:
                    memory: 4096M
                reservations:
                    memory: 2048M
