version: "3.3"

volumes:
    iredmail_vmail:
        external: true
    iredmail_clamav:
        external: true
    iredmail_mysql:
        external: true

networks:
    iredmail:
        external: true

services:
    iredmail:
        image: newtoncodes/iredmail:0.9.7
        ports:
            - 25:25
            - 587:587
            - 110:110
            - 143:143
            - 993:993
            - 995:995
        networks:
            - iredmail
        volumes:
            - iredmail_vmail:/var/vmail
            - iredmail_clamav:/var/lib/clamav
            - iredmail_mysql:/var/lib/mysql
        environment:
            - SOGO_WORKERS=2
            - DOMAIN=example.com
            - HOSTNAME=mail
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.role == manager
            resources:
                limits:
                    memory: 4096M
                reservations:
                    memory: 2048M

    snet:
        image: newtoncodes/snet:1.0.0
        networks:
            - iredmail
        environment:
            - PORTS=80:iredmail:80 443:iredmail:443
        volumes:
            - /etc/mothership/iredmail/vpn:/etc/snet
