version: "3.3"

volumes:
    youtrack_data:
        external: true
    youtrack_backup:
        external: true

networks:
    youtrack:
        external: true

services:
    youtrack:
        image: newtoncodes/youtrack:2017.4
        networks:
            - youtrack
        volumes:
            - youtrack_data:/opt/youtrack/data
            - youtrack_backup:/opt/youtrack/backup
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.role == manager
            resources:
                limits:
                    memory: 4096M
                reservations:
                    memory: 2048M
