version: "3.3"

volumes:
    youtrack_data:
        external: true
    youtrack_backup:
        external: true

networks:
    youtrack:
        external: true

services:
    youtrack:
        image: newtoncodes/youtrack:2017.4
        networks:
            - youtrack
        volumes:
            - youtrack_data:/opt/youtrack/data
            - youtrack_backup:/opt/youtrack/backup
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.role == manager
            resources:
                limits:
                    memory: 4096M
                reservations:
                    memory: 2048M

    nginx:
        image: newtoncodes/nginx
        ports:
            - 443:443
            - 80:80
        networks:
            - youtrack
        volumes:
            - /etc/mothership/youtrack/vhost.conf:/etc/nginx/vhosts/default.conf

    snet:
        image: newtoncodes/snet:1.0.0
        networks:
            - nginx
        environment:
            - PORTS=80:nginx:80 443:nginx:443
        volumes:
            - /etc/mothership/youtrack/vpn:/etc/snet